name: Sync Leetcode

on:
  workflow_dispatch:
#   schedule:
#     - cron:  '0 8 * * *'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: LeetCode Sync
      uses: dengl11/leetcode-sync@b17105d
      with:
        github-token: ${{ github.token }}
        leetcode-csrf-token: ${{ secrets.LEETCODE_CSRF_TOKEN }}
        leetcode-session: ${{ secrets.LEETCODE_SESSION }}
